version: '3.2'
services:
  os-dbt:
    image: onesignal/dbt
    build: .
    networks:
      - onesignal_default
    volumes:
      - './profiles.yml:/root/.dbt/profiles.yml'
      - './onesignal:/dbt'
    ports: 
      - '8580:8580'
networks:
  onesignal_default:
    external: true


      
