onesignal-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: os-postgres
      user: postgres
      pass: password
      port: 5432
      dbname: gamethrive
      schema: public
      threads: 4

airflow-presto:
  target: dev
  outputs:
    dev:
      type: presto
      host: airflow-presto
      user: dbt
      pass: password
      port: 8080
      database: hive
      schema: public
      threads: 4