---
onesignal-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: os-postgres
      user: postgres
      pass: password
      port: 5432
      dbname: gamethrive
      schema: public
      threads: 4
      