onesignal-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: os-postgres
      user: postgres
      pass: password
      port: 5432
      dbname: gamethrive
      schema: public
      threads: 4

presto-hive:
  target: prod
  outputs:
    prod:
      type: presto
      method: none
      host: 10.100.61.65
      user: dbt
      pass: password
      port: 8080
      catalog: hive
      schema: public
      threads: 1