presto-hive:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    prod:
      type: presto
      method: none
      host: "{{ env_var('DBT_PRESTO_HOST') }}"
      user: dbt
      pass: password
      port: "{{ env_var('DBT_PRESTO_PORT') }}"
      catalog: hive
      schema: public
      threads: 4